### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by HTV04** [thenumbernine/lua-parser#2]
This looks exactly like what I'm looking for, but I have no idea how to iterate over a tree to change elements. I've only been able to figure out how to generate a string by printing the tree.

**Comment by thenumbernine** [comment]
Hello, thanks , yeah I made this on a whim for a few other projects and never stopped to document it. 
I'll get around to doing that now and then I'll close this issue.
Thanks for the prompting.

**Comment by thenumbernine** [comment]
ok updated the readme for a basic reference of the API
