### ISSUE TITLE
Valid escape sequence \\n not tokenized properly

### ISSUE THREAD

**Issue by oezingle** [thenumbernine/lua-parser#9]
Lua allows for multiline strings not just with the `[[ .. ]]` syntax, but also:

```lua
local my_string = "Hello\
world!"
```
(In fact, lua's `%q` format specifier will default to using backslashes for multiline strings)

the tokenizer doens't see this as a valid escape sequence. Adding `['\n'] ="\n"` to `escapeCodes` in `base/tokenizer.lua:96` seems to remedy it, but I'm not as familiar with the tokenizer's internals anymore.

Here's a demo:
```lua
local LuaParser = require("lua-parser")

local chunk = [[
local my_string = "hello\
world"

print(my_string)
]]

local ast = LuaParser.parse(chunk)

local run_ast, err = load(tostring(ast), "rebuilt AST")

if not run_ast then
    error(err)
end

run_ast()
```

**Comment by thenumbernine** [comment]
Thanks very much for finding this. Fixed in the latest version.
